### ISSUE TITLE
Connection list latency when using tag tabs

### ISSUE THREAD

**Issue by majkinetor** [OneRemote/PRemoteM#236]
**Describe the bug**

There is a clear latency lasting for the duration of tag animation (sliding from the top). 

**To Reproduce**
Click fast concrete tag then All/Tags, then tag then All/Tags....

**Expected behavior**

Show connections immediately. Remove this tag on the top, we can already see what tab is selected and also tag in search field. There is no need to have 3 of them visible. Its also very annoying as are all animations.

**Comment by VShawn** [comment]
confirm, before i can figure out the latency, I will remove the animations.

> Remove this tag on the top, we can already see what tab is selected and also tag in search field.

It's a bug, I should show up only if the tag is not shown on the tab title.

found another bug:

![1](https://user-images.githubusercontent.com/10143738/168531021-90cb001a-8213-4a76-a17a-b5827cfce395.gif)

**Comment by majkinetor** [comment]
Perhaps its better to temporary add tab for tag that doesnt have it?

**Comment by VShawn** [comment]
@majkinetor 

This work correctly

![1](https://user-images.githubusercontent.com/10143738/168544037-44bdf5da-a94e-4de8-beef-7211a612de5c.gif)

**Comment by majkinetor** [comment]
OK, then that was a bug, and its better without animation.
